/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.f30l.interfaz;

import edu.f30l.decorator.IJugador;
import edu.f30l.entidades.Jugador;
import edu.f30l.entidades.Preguntas;

/**
 *
 * @author windows
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    IJugador jug;
    Preguntas preg;
    
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        jLblMensajeError.setVisible(false);
    }

    public void jugar(){
        String dif;
        if (jRbtnFacil.isSelected()){
            dif = jRbtnFacil.getText();
            preg = new Preguntas(1);
        }
        else if (jRbtnMedio.isSelected()){
            dif = jRbtnMedio.getText();
            preg = new Preguntas(2);
        }
        else{
            dif = jRbtnNormal.getText();
            preg = new Preguntas(3);
        }
        
        jug = new Jugador(jTxtNomJugador.getText(), 0, 1, dif,preg.getPreguntas());
        
        PantallaGeneral panDos = new PantallaGeneral();
        panDos.setVisible(true);
        panDos.traerDatos((Jugador)jug);
        this.setVisible(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rBtnDificultad = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTxtNomJugador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRbtnFacil = new javax.swing.JRadioButton();
        jRbtnMedio = new javax.swing.JRadioButton();
        jRbtnNormal = new javax.swing.JRadioButton();
        jBtnJugar = new javax.swing.JButton();
        jLblMensajeError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTxtNomJugador.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jTxtNomJugador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtNomJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomJugadorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(19, 56, 190));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione la dificultad");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(19, 56, 190));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INGRESE USUARIO: ");

        rBtnDificultad.add(jRbtnFacil);
        jRbtnFacil.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jRbtnFacil.setText("Facil");

        rBtnDificultad.add(jRbtnMedio);
        jRbtnMedio.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jRbtnMedio.setSelected(true);
        jRbtnMedio.setText("Medio");

        rBtnDificultad.add(jRbtnNormal);
        jRbtnNormal.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jRbtnNormal.setText("Normal");

        jBtnJugar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jBtnJugar.setForeground(new java.awt.Color(19, 56, 190));
        jBtnJugar.setText("Jugar");
        jBtnJugar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnJugarActionPerformed(evt);
            }
        });

        jLblMensajeError.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLblMensajeError.setForeground(new java.awt.Color(255, 0, 0));
        jLblMensajeError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblMensajeError.setText("Debe Ingresar un nombre de usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRbtnFacil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(jRbtnMedio)
                        .addGap(74, 74, 74)
                        .addComponent(jRbtnNormal))
                    .addComponent(jLblMensajeError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnJugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtNomJugador, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jTxtNomJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRbtnFacil)
                    .addComponent(jRbtnMedio)
                    .addComponent(jRbtnNormal))
                .addGap(70, 70, 70)
                .addComponent(jBtnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLblMensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnJugarActionPerformed
        if (!jTxtNomJugador.getText().equals(""))
            jugar();
        else
            jLblMensajeError.setVisible(true);
    }//GEN-LAST:event_jBtnJugarActionPerformed

    private void jTxtNomJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomJugadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnJugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLblMensajeError;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRbtnFacil;
    private javax.swing.JRadioButton jRbtnMedio;
    private javax.swing.JRadioButton jRbtnNormal;
    private javax.swing.JTextField jTxtNomJugador;
    private javax.swing.ButtonGroup rBtnDificultad;
    // End of variables declaration//GEN-END:variables
}
